### PR TITLE
BUILDING-WITH-BACKGROUNDS-AND-GRADIENTS

### PR DESCRIPTION
**Pull request by Salvador-ON**
This is the 3 project of Html & Css

Working with pictures in the background, color gradients and using different methods to align items.

### CODE REVIEW

**Comment by Salvador-ON** [comment]
fix some lint mistakes

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Great job @Salvador-ON :+1:, just a little change and you can :airplane:**
1. Your page comes up with a horizontal scroll. Kindly fix this.
image

Also, your live demo link is dead. Consider using raw.githack.com for your live demo.

Make these changes and submit another code review request.

**Happy coding:smile:**

**Comment by Salvador-ON** [comment]
fix horizontal scroll bar and live demo url

**Review by mosesogwo — APPROVED** [review]
**:trophy:Congratulations @Salvador-ON, your project is approved.**

You can now merge to master and submit a project completion form.

**Good luck in your next project.**

**Status: Approved.**

**Pull request merged**
